remote_theme: mmistakes/jekyll-theme-basically-basic

lang: de
title: Simon Gutwein
email: simon.bonvino@gmail.com
description: Simon Gutweins' Personal Webpage 
github_username: SimonBon
logo: assets/images/GITHUB_LOGO.png
url: simonbon.com
author: Simon Gutwein

navigation_pages:
  - HelloWorld.md
  - about.md

paginate: 5  # amount of posts to show per page
paginate_path: /page:num/