remote_theme: mmistakes/jekyll-theme-basically-basic

lang: de
title: MSc. Simon Gutwein
email: simon.bonvino@gmail.com
description: Simon Gutweins' Personal Webpage 
github_username: SimonBon
logo: assets/images/GITHUB_LOGO.png
url: simonbon.com
author: Simon Gutwein
